baseURL = "https://Ttuandatt.github.io/AWS-Workshop/"
publishDir = "public"
languageCode = "en-us"
title = "Daniel Phan Canh"
theme = "relearn"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# search
[outputs]
home = [ "HTML", "RSS", "JSON"]

# ------------------------------
# Params
# ------------------------------
[params]
  showLanguageSelector = true
  themeVariant = ["relearn-light", "relearn-dark"]
  alwaysShowThemeSwitcher = true

# ------------------------------
# Ngôn ngữ
# ------------------------------
[languages]

  [languages.en]
    title = "Internship Report"
    weight = 1
    languageName = "English"

  [languages.vi]
    title = "Báo Cáo Thực Tập"
    weight = 2
    languageName = "Tiếng Việt"

# ------------------------------
# Menu
# ------------------------------
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Worklog"
    url = "/worklog/"
    weight = 2

  [[menu.main]]
    name = "Proposal"
    url = "/proposal/"
    weight = 3

  [[menu.main]]
    name = "Translated Blogs"
    url = "/translated-blogs/"
    weight = 4

  [[menu.main]]
    name = "Events Participated"
    url = "/events/"
    weight = 5

  [[menu.main]]
    name = "Workshop"
    url = "/workshop/"
    weight = 6

  [[menu.main]]
    name = "Self Assessment"
    url = "/self-assessment/"
    weight = 7

  [[menu.main]]
    name = "Sharing and Feedback"
    url = "/feedback/"
    weight = 8

# config.toml
# baseURL cho local
[params]
  devBaseURL = "http://localhost:1313"